version: "3.3"
   
services:

  printer:
    build: ./printer_image
    restart: always
    command:  bash -c "sleep 1 && /bin/bash ./printer/run.sh"
    privileged: true
    # ports:
    #   - "8000:8000"
    volumes:
      - /dev:/dev
    environment:
      PYTHONIOENCODING: utf8

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: market
      POSTGRES_PASSWORD: 12345
      POSTGRES_USER: marketuser
    volumes:
      - ~/backups:/home/backups
      - ~/data/db:/var/lib/postgresql/data
    ports:
      - "5430:5432"

  web:
    build: .
    restart: always
    depends_on:
      - "db"
    command:  bash -c "sleep 1 && /bin/bash ./EasyPOS/run.sh"
    privileged: true
    ports:
      - "8000:8000"
    volumes:
      - ./POS/migrations:/root/EasyPOS/POS/migrations
      - /dev:/dev
    environment:
      POSTGRES_DB: market
      POSTGRES_PASSWORD: 12345
      POSTGRES_USER: marketuser
      DJANGO_SUPERUSER_PASSWORD: zzzz1963
      PYTHONIOENCODING: utf8