version: "3.3"
   
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: market
      POSTGRES_PASSWORD: 12345
      POSTGRES_USER: marketuser
    volumes:
      - ~/backups:/home/backups
      - ~/data/db:/var/lib/postgresql/data
    ports:
      - "5430:5432"

  web:
    build: .
    depends_on:
      - "db"
    network_mode: "host"
    command:  bash -c "sleep 1 && /bin/bash ./EasyPOS/run.sh"
    privileged: true
    volumes:
      - ./POS/migrations:/root/EasyPOS/POS/migrations
      - /dev:/dev
    environment:
      POSTGRES_DB: market
      POSTGRES_PASSWORD: 12345
      POSTGRES_USER: marketuser
      DJANGO_SUPERUSER_PASSWORD: zzzz1963
      PYTHONIOENCODING: utf8