# Generated by Django 3.2.8 on 2021-10-29 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('add_date', models.DateTimeField(verbose_name='date added')),
                ('price', models.FloatField()),
                ('bar', models.BigIntegerField(unique=True)),
                ('stock', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='sellReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('items', models.JSONField(default={})),
                ('add_date', models.DateTimeField(verbose_name='date added')),
                ('amount', models.FloatField(default=0)),
            ],
        ),
    ]
