# Generated by Django 3.2.8 on 2021-10-29 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellreceipt',
            name='items',
            field=models.JSONField(default={'items': [{}]}),
        ),
    ]
