# Generated by Django 3.2.9 on 2021-12-03 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='buyReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('items', models.JSONField(default={'items': {'__': {'bar': 0}}})),
                ('add_date', models.DateTimeField(verbose_name='date added')),
                ('amount', models.FloatField(default=0)),
            ],
        ),
    ]
