# Generated by Django 3.2.8 on 2021-10-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0002_alter_sellreceipt_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellreceipt',
            name='items',
            field=models.JSONField(default={'items': {'__': {'bar': 0}}}),
        ),
    ]
